# Stage 1: Build the React application
# FROM node:20.10.0 as build
FROM --platform=linux/amd64 node:20.10.0 as build

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Remove package-lock.json and node_modules if they exist
RUN rm -f package-lock.json && rm -rf node_modules

# Install the latest ajv and eslint to avoid problems
RUN npm install ajv@latest ajv-keywords@latest
RUN npm install eslint-webpack-plugin@latest schema-utils@latest

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the React application
RUN npm run build

# Stage 2: Serve the React application
FROM nginx:alpine

# Copy the build files from the previous stage
COPY --from=build /app/build /usr/share/nginx/html

# Copy a custom nginx configuration if needed
# COPY nginx.conf /etc/nginx/nginx.conf

# Expose port 80
EXPOSE 80

# Start Nginx server
CMD ["nginx", "-g", "daemon off;"]